<a href="https://colab.research.google.com/github/Qwerci/Pytorch-Tutorials/blob/main/learningpytorch00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pytorch Fundamentals

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


###Introduction to Tensors

In [4]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [7]:
#vector
vector = torch.tensor([2,4])
vector


tensor([2, 4])

In [8]:
vector.ndim


1

In [9]:
vector.shape

torch.Size([2])

In [11]:
# matrix

MATRIX = torch.tensor([[5,6],[3,5]])
MATRIX

tensor([[5, 6],
        [3, 5]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [5]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],[4,6,7],[4,6,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 6, 7],
         [4, 6, 9]]])

In [15]:
TENSOR.ndim

3

In [7]:
TENSOR.shape

torch.Size([1, 3, 3])

In [8]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 6, 7],
        [4, 6, 9]])

In [9]:
## Random tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8668, 0.7533, 0.1675, 0.4933],
        [0.2585, 0.3741, 0.8929, 0.2192],
        [0.5489, 0.2338, 0.8258, 0.4298]])

In [10]:
random_tensor.ndim

2

In [11]:
random_tensor.shape

torch.Size([3, 4])

In [12]:
#create a random tensor similar to image

random_image_size_tensor = torch.rand((224, 224,3),)
random_image_size_tensor

tensor([[[0.1597, 0.8245, 0.4993],
         [0.9500, 0.7452, 0.5978],
         [0.8879, 0.1941, 0.4694],
         ...,
         [0.8088, 0.1958, 0.1306],
         [0.4623, 0.4662, 0.7673],
         [0.3107, 0.1480, 0.7447]],

        [[0.9286, 0.2868, 0.8546],
         [0.8175, 0.2704, 0.7968],
         [0.9499, 0.6535, 0.9768],
         ...,
         [0.0808, 0.3442, 0.8497],
         [0.7285, 0.6595, 0.1981],
         [0.0027, 0.8016, 0.8473]],

        [[0.9611, 0.1946, 0.3913],
         [0.4412, 0.1976, 0.4329],
         [0.9928, 0.8129, 0.9355],
         ...,
         [0.6698, 0.0231, 0.3319],
         [0.3002, 0.5946, 0.5379],
         [0.2087, 0.0483, 0.9322]],

        ...,

        [[0.5608, 0.1876, 0.9947],
         [0.4309, 0.8994, 0.1083],
         [0.2809, 0.5957, 0.4491],
         ...,
         [0.4270, 0.9782, 0.4139],
         [0.8270, 0.1819, 0.9650],
         [0.4195, 0.4276, 0.5918]],

        [[0.7368, 0.5477, 0.5442],
         [0.6084, 0.0979, 0.3894],
         [0.

Zeros and ones



In [ ]:
Zeros and ones

In [15]:
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range tensor and tensors-like

In [18]:
torch.arange((1,11))


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Manipulating Tensor (tensor operations)


Addition


In [5]:
tensor = torch.tensor([9,7,7])
tensor + 10


tensor([19, 17, 17])

In [6]:
tensor.add(10)

tensor([19, 17, 17])

Subtraction

In [3]:
tensor - 10

tensor([-1, -3, -3])

In [9]:
tensor.subtract(10)

tensor([-1, -3, -3])

Multiplication

In [10]:
tensor * 10

tensor([90, 70, 70])

In [11]:
tensor.mul(10)

tensor([90, 70, 70])

Division

In [12]:
tensor/3

tensor([3.0000, 2.3333, 2.3333])

In [13]:
tensor.div(3)

tensor([3.0000, 2.3333, 2.3333])

Matrix multiplication

    1.Element-wise multiplication 
    2. matrix multiplication

Element-wise multiplication


In [5]:
tensor = torch.tensor([2,3,4])

In [8]:
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([2, 3, 4]) * tensor([2, 3, 4])
Equals: tensor([ 4,  9, 16])


Matrix multiplication

In [9]:
ten_matrix = torch.matmul(tensor, tensor)
ten_matrix

tensor(29)

In [10]:
tensor @ tensor

tensor(29)

###Tensor Aggregation(min, max, mean, sum, etc)

In [13]:
# create a tensor

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
# Finding the min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [17]:
# Finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [18]:
#finding the mean

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [20]:
# finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [23]:
x.argmin()

tensor(0)

In [24]:
x.argmax()

tensor(9)